import './globals.css';
import { Inter, Plus_Jakarta_Sans } from 'next/font/google';
import Header from './header';

const inter = Inter({ subsets: ['latin'] });
const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body className={`${jakarta.className}`}>
        <nav className="bg-gray-800">
          <div className=" mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
            <Header />
          </div>
        </nav>
        <div className=" mx-auto max-w-7xl px-2 sm:px-6 lg:px-8 ">
          {children}
        </div>
      </body>
    </html>
  );
}
